language: elixir

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.3
      elixir: 1.5
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 21.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.1

env:
  global:
    - MIX_ENV=test

sudo: true

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

install:
  - mix local.rebar --force
  - mix local.hex --force

script:
  - source $HOME/.cargo/env
  - cargo test
  - cd rustler_mix && mix do deps.get, test && cd -
  - cd rustler_tests && mix do deps.get, test && cd -
