language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get -qq update
  - sudo apt-get install -y erlang elixir tree
  - mix local.hex --force
  - erl -version
  - elixir --version
  - mix --version

script:
  - cargo build --verbose
  - cd test && mix test

after_script:
  - tree
