[package]
name = "rustler"
description = "Safe Rust wrappers for creating Erlang NIF functions"
repository = "https://github.com/hansihe/Rustler"
version = "0.12.0"
authors = ["Hansihe <me@hansihe.com>"]
license = "MIT/Apache-2.0"

[dependencies]
erlang_nif-sys = ">=0.5"
lazy_static = "0.1.*"
