[package]
name = "rustler_test"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]
edition = "2018"

[lib]
name = "rustler_test"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.2"
rustler = { path = "../../../rustler" }
