[package]
name = "rustler_test"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustler_test"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "hello_rust"
path = "src/main.rs"

[dependencies]
lazy_static = "1.4"
rustler = { path = "../../../rustler" }
