[package]
name = "rustler_test"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[lib]
name = "rustler_test"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.0"
rustler = { path = "../rustler" }
rustler_codegen = { path = "../rustler_codegen" }
