[package]
name = "rustler_codegen"
description = "Compiler plugin for Rustler"
repository = "https://github.com/hansihe/rustler/tree/master/rustler_codegen"
version = "0.20.0" # rustler_codegen version
authors = ["Hansihe <hansihe@hansihe.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "rustler_codegen"
proc_macro = true

[dependencies]
syn = { version = "0.15.24", features = ["derive"] }
quote = "0.6.10"
heck = "0.3"
proc-macro2 = "0.4"
