[package]
name = "rustler_codegen"
description = "Compiler plugin for Rustler"
repository = "https://github.com/hansihe/Rustler/tree/master/rustler_codegen"
version = "0.13.0"
authors = ["Hansihe <hansihe@hansihe.com>"]
license = "BSD-2-Clause"

[lib]
name = "rustler_codegen"
proc_macro = true

[dependencies]
syn = { version = "0.11.4", features = ["aster", "visit"] }
quote = "0.3.12"
