[package]
name = "dynamic_load"
version = "0.1.0"
edition = "2021"

[lib]
name = "dynamic_load"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { path = "../../../rustler", features = ["big_integer", "allocator"] }
