[package]
name = "cargo-rustler"
version = "0.1.0"
edition = "2021"

metadata = { msrv = "1.77" }

[dependencies]
cargo_metadata = "0.21.0"
clap = { version = "4.5", features = [ "derive" ] }
libloading = "0.8"
tempfile = "3.19.1"
