name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: '0 0 * * 3'

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

  clippy-windows:
    name: Clippy-Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Erlang/Elixir
        run: choco install elixir
      - name: Extend PATH
        run: echo "C:\\ProgramData\\chocolatey\\lib\\Elixir\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build API
        working-directory: rustler_sys
        run: |
            cargo build
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true

      - name: Install Erlang/Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "25.0.0"
          elixir-version: "1.13.4"

      - name: Check cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check mix format (rustler_mix)
        working-directory: rustler_mix
        run: mix format --check-formatted

      - name: Check mix format (rustler_tests)
        working-directory: rustler_tests
        run: mix format --check-formatted

  rustler_mix_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Erlang/Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "24.1.7"
          elixir-version: 1.13

      - name: Test rustler_mix
        working-directory: rustler_mix
        run: ./test.sh

  test_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Erlang/Elixir
        run: choco install elixir

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Extend PATH
        run: echo "C:\\ProgramData\\chocolatey\\lib\\Elixir\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Hex
        run: mix local.hex --force

      - name: Test rustler_mix
        working-directory: rustler_mix
        run: |
          mix deps.get
          mix test

      - name: Test rustler_tests
        working-directory: rustler_tests
        run: |
          mix deps.get
          mix test

  test:
    name: OTP ${{matrix.pair.erlang}} / Elixir ${{matrix.pair.elixir}} / Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - { erlang: "25.0.0", elixir: "1.13.4" }
          - { erlang: "24.3.4", elixir: "1.13.0" }
          - { erlang: "24.3.4", elixir: "1.12.3" }
          - { erlang: "24.3.4", elixir: "1.11.4" }
          - { erlang: "23.3.4.14", elixir: "1.11.4" }
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Erlang/Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          override: true

      - run: cargo test

      - name: Test rustler_mix
        working-directory: rustler_mix
        run: |
          mix deps.get
          mix test

      - name: Test rustler_tests
        working-directory: rustler_tests
        run: |
          mix deps.get
          mix test

  test_macos:
    name: macos-11 test
    runs-on: macos-11
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Erlang/Elixir
        run: |
          brew install elixir
          mix local.hex --force

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo test

      - name: Test rustler_mix
        working-directory: rustler_mix
        run: |
          mix deps.get
          mix test

      - name: Test rustler_tests
        working-directory: rustler_tests
        run: |
          mix deps.get
          mix test
